on:
  release:
    types: [created, edited]
jobs:
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: download web
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: HTML5.zip
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: release web
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: web
          ITCH_GAME: Space Race
          ITCH_USER: etmitchell2022
          PACKAGE: HTML5.zip
