on:
  push:
    branches:
      - main
jobs:
  release_web:
    runs-on: ubuntu-latest
    steps:
      - name: download web
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: SpaceRace.zip
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: release web
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: HTML
          ITCH_GAME: space-race
          ITCH_USER: etmitchell2022
          PACKAGE: SpaceRace.zip
